name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repository
        uses: actions/checkout@v2

      - name: Upload Files
        uses: dennisameling/ftp-upload-action@v1
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ./src/
          server_dir: public_html/banner/api/
          secure: false
